apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redia-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - {{ .Values.redia.env.domainName }}
    secretName: letsencrypt-prod
  rules:
  - host: {{ .Values.redia.env.domainName }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: redia-service
            port:
              number: 3000
