apiVersion: v1
kind: Secret
metadata:
  name: redia-secret
type: Opaque
data:
  EMAIL_HOST: {{ required "The emailHost for redia is required" .Values.redia.env.emailHost | b64enc }}
  EMAIL_PORT: {{ required "The emailPort for redia is required" .Values.redia.env.emailPort | quote | b64enc }}
  EMAIL_USER: {{ required "The emailUser for redia is required" .Values.redia.env.emailUser | b64enc }}
  EMAIL_PASS: {{ required "The emailPass for redia is required" .Values.redia.env.emailPass | b64enc }}
